export default function Reducer(
  state = {
    mobile: [
      {
        model: "Iphone12",
        brand: "Apple",
        year: "2017",
        memory: "128GB",
        color: "white",
        screen: "5",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "Iphone12",
        brand: "Apple",
        year: "2017",
        memory: "128GB",
        color: "white",
        screen: "5",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "Iphone12",
        brand: "Apple",
        year: "2017",
        memory: "128GB",
        color: "white",
        screen: "5",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "Iphone12",
        brand: "Apple",
        year: "2018",
        memory: "128GB",
        color: "white",
        screen: "5",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "Iphone11",
        brand: "Apple",
        year: "2019",
        memory: "128GB",
        color: "back",
        screen: "4",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "Nokia XL",
        brand: "Nokia",
        year: "2019",
        memory: "64GB",
        color: "back",
        screen: "4",
        dualSIM: false,
        NFC: false,
        fourg: true,
      },
      {
        model: "Iphone12 pro",
        brand: "Apple",
        year: "2020",
        memory: "128GB",
        color: "white",
        screen: "3",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "Iphone12 pro",
        brand: "Apple",
        year: "2020",
        memory: "128GB",
        color: "white",
        screen: "3",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "Iphone12 pro",
        brand: "Apple",
        year: "2020",
        memory: "128GB",
        color: "white",
        screen: "3",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "Iphone12 pro",
        brand: "Apple",
        year: "2020",
        memory: "128GB",
        color: "white",
        screen: "3",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "Iphone12 pro",
        brand: "Sony",
        year: "2020",
        memory: "128GB",
        color: "white",
        screen: "3",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "lg pro",
        brand: "LG",
        year: "2020",
        memory: "128GB",
        color: "white",
        screen: "3",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
      {
        model: "sumsang pro",
        brand: "Samsung",
        year: "2020",
        memory: "128GB",
        color: "white",
        screen: "3",
        dualSIM: true,
        NFC: true,
        fourg: true,
      },
    ],
  },
  action
) {
  switch (action.type) {
    case "ADD_MOBILE":
      return (state = {
        mobile: [...state.mobile, action.payload],
      });
    default:
      return state;
  }
}